# Generated by Django 4.0.1 on 2022-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tripName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='userName',
            field=models.TextField(),
        ),
    ]
